// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhXEYweXKjVctvG4fWStGhxKq5MIbuLmQ',
    appId: '1:814319835696:web:012251ad94eeac6812ebf5',
    messagingSenderId: '814319835696',
    projectId: 'doc-app-6f936',
    authDomain: 'doc-app-6f936.firebaseapp.com',
    storageBucket: 'doc-app-6f936.firebasestorage.app',
    measurementId: 'G-QQCC6Z7786',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2pyuEZpiVmLcxgjj-7ST21eiBVDy7YZQ',
    appId: '1:814319835696:android:0a924650adcbea1f12ebf5',
    messagingSenderId: '814319835696',
    projectId: 'doc-app-6f936',
    storageBucket: 'doc-app-6f936.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsNqEgn7Opcs93Ys9OHT_AuFLGUDN5TE',
    appId: '1:814319835696:ios:fe5dbc76cabe3e2e12ebf5',
    messagingSenderId: '814319835696',
    projectId: 'doc-app-6f936',
    storageBucket: 'doc-app-6f936.firebasestorage.app',
    iosBundleId: 'com.example.docApp',
  );
}
